### PR TITLE
Add version-independent bit library

### PR DESCRIPTION
**Pull request by RyanSquared**

### CODE REVIEW

**Comment by RyanSquared** [comment]
TODO: add installation of bitop to tests

**Comment by leafo** [comment]
we gotta make the specs work

**Comment by leafo** [comment]
Going to fix the build?

**Comment by RyanSquared** [comment]
Right, sorry about that. I had something locally that I thought I pushed, and unfortunately I cleaned up some "testing" folders in my homedir that actually contained my local `pgmoon` setup. I'll try to recreate it and push to master.

**Comment by leafo** [comment]
I'm closing this since we got another implementation merged. Thanks for submitting a pull request.

**Pull request closed without merging**
