### PR TITLE
Support HAProxy socket type from init configuration

### PR DESCRIPTION
**Pull request by mecampbellsoup**
Related to https://github.com/leafo/pgmoon/issues/114.

### CODE REVIEW

**Comment by mecampbellsoup** [comment]
@leafo could you take a look please when you have a minute? Thanks 😄

**Comment by mecampbellsoup** [comment]
@leafo I guess I should've made the changes to the moon files instead of the `.lua` files and then run `make build` to generate the Lua file changes?

**Comment by mecampbellsoup** [comment]
Hi @leafo, do you know when we might expect your review? Thank you.

**Comment by leafo** [comment]
The only unanswered issue is about the `core` global. Is that really the only way to access haproxy, a global variable named `core`?

**Comment by mecampbellsoup** [comment]
> The only unanswered issue is about the `core` global. Is that really the only way to access haproxy, a global variable named `core`?

https://www.arpalert.org/src/haproxy-lua-api/1.6/index.html#core-class

**Comment by mecampbellsoup** [comment]
Hi @leafo we are still maintaining our fork and it's a bit cumbersome, did I answer your question about the `core` class?

**Comment by mecampbellsoup** [comment]
> Hi @leafo we are still maintaining our fork and it's a bit cumbersome, did I answer your question about the `core` class?

@leafo ping, please let us know your thoughts on this PR 🙏

**Comment by mecampbellsoup** [comment]
Closing in favor of https://github.com/leafo/pgmoon/pull/125.

**Pull request closed without merging**
