### PR TITLE
cleartext auth

### PR DESCRIPTION
**Pull request by 8026787**
implementation of AuthenticationCleartextPassword 
if you don't mind

### CODE REVIEW

**Comment by leafo** [comment]
I don't mind, but this project is written in [moonscript](http://moonscript.org/). If you don't want to convert your patch I'll rewrite your code for you.

**Comment by 8026787** [comment]
I'm not really confident in moonscript, so if you can rewrite it by yourself it would be nice

**Comment by leafo** [comment]
Okay, going to leave this open in the meantime as a reminder

**Comment by starius** [comment]
By the way, it also fixes the following error (luacheck):
```
init.lua:221:69: accessing undefined variable auth_type
```

**Comment by starius** [comment]
@8026787, I have implemented the same code in moonscript: https://github.com/8026787/pgmoon/pull/1
Can you test and merge it, please?

**Pull request closed without merging**
